module.exports = {
  xs: "var(--box-shadow-xs)",
  sm: "var(--box-shadow-sm)",
  default: "var(--box-shadow-default)",
  md: "var(--box-shadow-md)",
  lg: "var(--box-shadow-lg)",
  xl: "var(--box-shadow-xl)",
  "2xl": "var(--box-shadow-2xl)",
  inner: "var(--box-shadow-inner)",
  none: "var(--box-shadow-none)",
  solid: "0 0 0 2px currentColor",
  outline: "var(--box-shadow-outline)",
  "outline-gray": "var(--box-shadow-outline-gray)",
  "outline-primary": "var(--box-shadow-outline-primary)",
  "outline-success": "var(--box-shadow-outline-success)",
  "outline-danger": "var(--box-shadow-outline-danger)",
  "outline-warning": "var(--box-shadow-outline-warning)",
  "outline-info": "var(--box-shadow-outline-info)",
  "outline-urge": "var(--box-shadow-outline-urge)",
};
