export default (theme, { breakpoints }) => ({
  none: "none",
  xs: "var(--max-width-xs)",
  sm: "var(--max-width-sm)",
  md: "var(--max-width-md)",
  lg: "var(--max-width-lg)",
  xl: "var(--max-width-xl)",
  "2xl": "var(--max-width-2xl)",
  "3xl": "var(--max-width-3xl)",
  "4xl": "var(--max-width-4xl)",
  "5xl": "var(--max-width-5xl)",
  "6xl": "var(--max-width-6xl)",
  full: "100%",
  ...breakpoints(theme("screens")),
});
